collector:
  exchange:
    name: Bitfinex
    timeframes:
      - 1m
      - 5m
      - 15m
      - 30m
      - 1h
      - 3h
      - 6h
    symbolpairs:
      - BTCUSD
      - XRPUSD
      - ETHUSD
      - LTCUSD
      - XRPBTC
      - ETHBTC
      - LTCBTC

server:
  context-path: /bitfinex