collector:
  exchange:
    name: Binance
    symbolpairs:
      - BTCUSDT
      - ETHUSDT
      - LTCUSDT
      - XRPBTC
      - ETHBTC
      - LTCBTC
    timeframes:
      - 1m
      - 5m
      - 15m
      - 30m
      - 1h
      - 4h
      - 6h

server:
  context-path: /binance
  port: 8081
